const express = require('express');
const router = express.Router();
const UserController = require('../controllers/userController');
const authMiddleware = require('../middlewares/authMiddleware');
const rateLimit = require('../middlewares/rateLimit');
const authLimit = rateLimit({ windowMs: 15 * 60 * 1000, max: 20 });
const otpLimit = rateLimit({ windowMs: 15 * 60 * 1000, max: 5 });

router.post('/signup', authLimit, UserController.createUser);
router.post('/signin', authLimit, UserController.signin);
router.post('/google-signin', authLimit, UserController.googleSignin);
router.post('/send-login-otp', otpLimit, UserController.sendLoginOtp);
router.post('/send-signup-otp', otpLimit, UserController.sendLoginOtp);
router.get('/profile', authMiddleware, UserController.getUserProfile);
router.put('/profile', authMiddleware, UserController.updateUserProfile);
router.put('/password', authMiddleware, UserController.changePassword);
router.post('/address', authMiddleware, UserController.createUserAddress);
router.put('/address/:addressId', authMiddleware, UserController.updateUserAddress);
router.delete('/address/:addressId', authMiddleware, UserController.deleteUserAddress);
module.exports = router;
